### ISSUE TITLE
Question: hasOnlySubstanceUnits

### ISSUE THREAD

**Issue by thomassligon** [ICB-DCM/AMICI#1011]
I am getting this warning
`2020-03-15 19:22:08.022 - amici.petab_import - WARNING - Ignoring s96 which has only substance units. Conversion not yet implemented.`
236 times. The model contains 342 species, and 236 of them have
`hasOnlySubstanceUnits="true"`
in SBML. I have no idea where this came from or why, but CellDesigner documents it clearly in the UI.
The SBML documentation states:

> The role of the attribute 'hasOnlySubstanceUnits' is to indicate whether the units of the species, when the species identifier appears in mathematical formulas, are intended to be concentration or amount. The attribute takes on a boolean value. In SBML Level 3, the attribute has no default value and must always be set in a model; in SBML Level 2, it has a default value of false.

It might have a meaning, such as setting genes to amount and proteins to concentration, but the model seems to be more a matter of chance.
Do we have any recommendations for this?

**Comment by FFroehlich** [comment]
> 4.6.5 The hasOnlySubstanceUnits attribute
Independently from how the initial value of a species’ quantity is set (Section 4.6.4), SBML allows choosing the meaning intended for a species’ identifier when the identifier appears in mathematical expressions or as the subject of SBML rules or assignments. The interpretation is controlled by the attribute hasOnlySubstanceUnits. If the attribute has the value “ false“, then the unit of measurement associated with the value of the species is {unit of amount}/{unit of size} (i.e., concentration or density). If hasOnlySubstanceUnits has the value “ true“, then the value is interpreted as having a unit of amount only.

`hasOnlySubstanceUnits` has a very specific meaning that impacts simulation results. Setting it true or false should always be intentional.

**Comment by thomassligon** [comment]
Thanks for the comments. Now I see that {unit of size} is not used when `hasOnlySubstanceUnits `is true, so a change in the volume of a compartment shouldn't affect the calculation. Now, in a typical biological model, I can understand how to use concentration or density for many types of species, such as proteins and also genes. Sometimes, this can also refer to the number of molecules, which can be useful for genes and in stochastic simulation. Now I also searched for concrete examples in
http://sbml.org/Special/specifications/sbml-level-3/version-2/core/release-1/sbml-level-3-version-2-core.pdf
and I see that almost all of them use "false". The very few that use "true" could probably have been formulated to use "false" instead. In summary, I have trouble finding any cases where it would be necessary to use "true".
The model I am working on was a "cartoon-only" model when I inherited it, so all instances of units, concentration, rates, etc. are things that I have been adding as I gradually improve the model, and "false" fits this better than "true".
