### ISSUE TITLE
SBML import: Better handling of maximum identifier length for symbolic

### ISSUE THREAD

**Issue by dweindl** [ICB-DCM/AMICI#128]
If parameter names in SBML are too long, SBML2AMICI fails with:

> Error using SBMLode/checkODE (line 11)
Some parameters have identifiers are longer than 63 which MATLAB cannot handle, please shorten the identifiers!

It would be more user-friendly if this was checked right in the beginning, since for large models, it may take several minutes to fail.

It would be even more user-friendly if the names would be replaced internally by something with feasible length. E.g. replacing common substrings.

**Comment by FFroehlich** [comment]
I fully agree that this should be checked earlier. https://github.com/ICB-DCM/AMICI/issues/50 will probably require this one way or another.

Replacing common substrings is a bit difficult because you need to ensure that the symbolic variables remain globally unique (SBML id's are guaranteed to be), so you can only remove expressions that are common across parameters, states, rules etc, which will probably never be the case.
