### ISSUE TITLE
Move application of chain rule factor from .m to .c

### ISSUE THREAD

**Issue by dweindl** [ICB-DCM/AMICI#41]
Include field to parameter type in UserData, apply chain rule factor in amici.cpp, remove respective code from simulate___.m

**Comment by paulstapor** [comment]
I added a new option to amioption: pscale. it can be set to 'lin' or 1, 'log' or 2, 'log10' or 3. This options is checked and then sets udata->am_pscale accordingly.
So in some future, the simulate_### file will look differently. This means that people who recompile an existing model with the new Amici-Version will need set one more option in order to make existing code work again, or am I mistaken?
