### ISSUE TITLE
Questions 2018-09-03

### ISSUE THREAD

**Issue by thomassligon** [ICB-DCM/AMICI#427]
AMICI questions 2018-09-03
1) linsol
The code I am using has a line
            options = amioption();
After that line, options.linsol=9, which means KLU (Sparse). However, the header in the script simulate_... says that the default is 1 (Dense).
Has the default been changed?

2) newton options
The code I am using also has the following lines:
            options.newton_maxsteps = 0;
%             options.newton_preeq = 0;
%             options_Preequilibration.newton_preeq = 0;
The header in the script simulate_... contains the word newton only once:
%    .iter    ... iteration method for linear multistep.
%        1: Functional
%        2: Newton (DEFAULT)
Does this mean that Newton is the default for linear multistep? 
What do newton_maxteps and newton_preeq mean=? What is default? How should they be used? 
How do I turn the Newton solver off completely?

3) sensi
The code I am using has the following lines:
            options.sensi = 0;
            options.sensi_meth=0;
In the header in the script simulate_..., options.sensi is not documented at all, and options.sensi_meth can only have values 1 and 2, so I don't know what 0 means.
What do these 2 lines mean?

4) KLU factorization failed!
I recently had this error message, so I tried to find out where it was coming from.
File parPE/deps/AMICI/src/newton_solver.cpp (file date 2018-06-27) contains the message.
File AMICI/src/newton_solver.cpp (file date 2018-08-25) does not contain the message.
Why does AMICI create a mex file containing a module from parPE and not use its own version?
Why does parPE need to keep a copy of AMICI source files?
What do I need to do in order to avoid creating a mex consisting of different versions of the AMICI code?

5) AMICI error in module cvKLUSetup: A call to an external package failed
When I had this error message, I searched (grepped) to find where it was coming from, and found the following files:
parPE/deps/AMICI/ThirdParty/sundials/src/cvodes/cvodes_klu.c (file date 2018-06-27)
parPE/deps/AMICI/ThirdParty/sundials/src/cvode/cvode_klu.c (file date 2018-06-27)
AMICI/ThirdParty/sundials/src/cvodes/cvodes_klu.c (file date 2018-06-17)
AMICI/ThirdParty/sundials/src/cvode/cvode_klu.c (file date 2018-06-17)
LargeScaleOptimization/FabisCode/Auswertungsroutinen/supplement_code/ICB-DCM-AMICI-35f18fe/sundials/src/cvodes/cvodes_klu.c (file date 2018-05-25)
LargeScaleOptimization/FabisCode/Auswertungsroutinen/supplement_code/ICB-DCM-AMICI-35f18fe/sundials/src/cvode/cvode_klu.c (file date 2018-05-25)
Does this mean that my code is using a sparse solver (options.iter=2)?
Is this what it should be using?
Which version of cvode(s)_klu.c does AMICI use to create the mex file?
Why do parPE and LargeScaleOptimization need to keep copies of AMICI source files?
What do I need to do in order to avoid creating a mex consisting of different versions of the AMICI code?

**Comment by FFroehlich** [comment]
> linsol
The code I am using has a line
options = amioption();
After that line, options.linsol=9, which means KLU (Sparse). However, the header in the script simulate_... says that the default is 1 (Dense).
Has the default been changed?

The default is options.linsol=9, i.e. a sparse solver

>newton options
The code I am using also has the following lines:
options.newton_maxsteps = 0;
% options.newton_preeq = 0;
% options_Preequilibration.newton_preeq = 0;
The header in the script simulate_... contains the word newton only once:
% .iter ... iteration method for linear multistep.
% 1: Functional
% 2: Newton (DEFAULT)
Does this mean that Newton is the default for linear multistep?
What do newton_maxteps and newton_preeq mean=? What is default? How should they be used?
How do I turn the Newton solver off completely?

I think support for the newton solver was never update in the matlab solver interface. options.newton_maxsteps = 0 will disable the newton solver and enforce simulation-base preequilibration.

> sensi
The code I am using has the following lines:
options.sensi = 0;
options.sensi_meth=0;
In the header in the script simulate_..., options.sensi is not documented at all, and options.sensi_meth can only have values 1 and 2, so I don't know what 0 means.
What do these 2 lines mean?

The meaning of values for sensi_meth are defined as enum class
```
/** methods for sensitivity computation */
enum class SensitivityMethod {
    none,
    forward,
    adjoint
};
```
0 corresponds to no active sensitivity method, this is bound to cause issues in combination with `options.newton_maxsteps = 0;`

The meaning of values for sensi are also defined as enum class
```
/** orders of sensitivity analysis */
enum class SensitivityOrder {
    none,
    first,
    second
};
```

> KLU factorization failed!
I recently had this error message, so I tried to find out where it was coming from.
File parPE/deps/AMICI/src/newton_solver.cpp (file date 2018-06-27) contains the message.
File AMICI/src/newton_solver.cpp (file date 2018-08-25) does not contain the message.
Why does AMICI create a mex file containing a module from parPE and not use its own version?
Why does parPE need to keep a copy of AMICI source files?
What do I need to do in order to avoid creating a mex consisting of different versions of the AMICI code?

You probably have to ask most of these questions to @dweindl. Apparently `parPE` includes it's own (old) version of AMICI.

"KLU factorization failed!" indicates that there was a problem with the factorization of the Jacobian which is likely due to the fact that the Jacobian does not have full rank.

> AMICI error in module cvKLUSetup: A call to an external package failed
When I had this error message, I searched (grepped) to find where it was coming from, and found the following files:
parPE/deps/AMICI/ThirdParty/sundials/src/cvodes/cvodes_klu.c (file date 2018-06-27)
parPE/deps/AMICI/ThirdParty/sundials/src/cvode/cvode_klu.c (file date 2018-06-27)
AMICI/ThirdParty/sundials/src/cvodes/cvodes_klu.c (file date 2018-06-17)
AMICI/ThirdParty/sundials/src/cvode/cvode_klu.c (file date 2018-06-17)
LargeScaleOptimization/FabisCode/Auswertungsroutinen/supplement_code/ICB-DCM-AMICI-35f18fe/sundials/src/cvodes/cvodes_klu.c (file date 2018-05-25)
LargeScaleOptimization/FabisCode/Auswertungsroutinen/supplement_code/ICB-DCM-AMICI-35f18fe/sundials/src/cvode/cvode_klu.c (file date 2018-05-25)
Does this mean that my code is using a sparse solver (options.iter=2)?
Is this what it should be using?
Which version of cvode(s)_klu.c does AMICI use to create the mex file?
Why do parPE and LargeScaleOptimization need to keep copies of AMICI source files?
What do I need to do in order to avoid creating a mex consisting of different versions of the AMICI code?

see above

**Comment by dweindl** [comment]
Hi Tom, please only report AMICI issues here, and parPE issues in the respective repository.

> Why does AMICI create a mex file containing a module from parPE and not use its own version?

That pretty much depends on what you specified in your matlab path.

> Why does parPE need to keep a copy of AMICI source files?

For the user's convenience. To ensure, that the API matches the expectations. If you are only using the script for python hdf5 generation this shouldn't matter too much (no guarantee though).

> What do I need to do in order to avoid creating a mex consisting of different versions of the AMICI code?

If you have only one AMICI version in your matlab path, no such thing should happen. If it still happens, although unlikely, this could be a caching issue and deleting the respective `models/`folder and rerunning `amiwrap` should do the trick.

**Comment by thomassligon** [comment]
I have created a modified version of
[generateMatlabWrapper.zip](https://github.com/ICB-DCM/AMICI/files/2348080/generateMatlabWrapper.zip)
I wanted to create a pull request, but it looks like I don't have permissions to create a new branch (I don't need that).

**Comment by thomassligon** [comment]
My MATLAB path does NOT include parPE or LargeScaleOptimization. Even if it did, this remark would mean that mex was using the MATLAB path to compile and line C++ files, which I find very unlikely. I think that the path is buried somewhere in the AMICI mex files. By the way, I didn't "install" ParPE or LargeScaleOptimization; I only cloned them and copied 1 Python file from ParPE and 2 MATLAB files from LargeScaleOptimization. There should be no reason for any C++ sources from these directories to be used by mex.

**Comment by dweindl** [comment]
> I wanted to create a pull request, but it looks like I don't have permissions to create a new branch

Not sure why, since it obviously worked in #308, but it created one for you: #429.

>[previous post]

I am not sure if I understood the problem correctly then.

**Comment by thomassligon** [comment]
Thanks for the help. The answers to the first 3 questions were very useful. The other 2 questions (KLU) are probably not worth pursuing at this time. I didn't find anything in the MATLAB or Windows path that would explain problem 4, and AMICI doesn't contain such a reference. There are more interesting things to look at now, so I'll close the request.
