### ISSUE TITLE
negative concentrations

### ISSUE THREAD

**Issue by thomassligon** [ICB-DCM/AMICI#441]
This message describes cases that cause concentrations to move into negative ranges, sometimes achieving large negative values. The problem occurs during simulation both in Copasi and AMICI. AMICI once had a flag to enforce positive values, but that has been changed and it is currently not clear what the best solution is.

As a warning, I should say that I might be provoking the problem more than necessary. My goal is to use literature-based parameter values, but this is at an early stage and might include some miscalculations.

As a background, let's take a look at degradation with the following reaction:
`-kdeg*substrate1`
Normally, the closer substrate1 gets to zero, the slower the reaction, but what happens if substrate1 attains a slightly negative value due to numerical errors? Then, the degradation will be positive and will correct the error.

Now let's look at dimerization and, for simplicity, just consider an irreversible reaction, where substrate1 is consumed by dimerization:
`-kon*substrate1^2`
Now, if substrate1 reaches a slightly negative value, substrate1^2 will still be positive, and substrate1 will go into larger and larger negative values.
We tried to fix this by using the following reaction:
`-kon*max(substrate1,0)*substrate1`

According to http://sbml.org/Facilities/Validator, the SBML is valid.

Copasi doesn't accept the formula:
SBML (76): Unable to resolve dependencies for the following function definitions:
"Complex_Formation_2_substrates__rev".
The error message isn't documented in Copasi, and I didn't find it in libSBML, so I requested clarification.

AMICI doesn't accept the formula:
Error using symengine
Input arguments must be convertible to floating-point numbers.
Error in sym/privBinaryOp (line 1013)
            Csym = mupadmex(op,args{1}.s, args{2}.s, varargin{:});
Error in sym/max (line 73)
        C = privBinaryOp(X, Y, 'symobj::zipWithImplicitExpansion', 'symobj::maxComplex');
Error in ASTHMA_V40_M07_syms>Complex_Formation_2_substrates__rev (line 614)
`    r = kon*max(substrate1,0)*substrate2-koff*product;`
Error in ASTHMA_V40_M07_syms (line 55)
Protein_Production_and_Degradation(kprod_re639, s2092, kdeg_re639) - Complex_Formation_2_substrates__rev(kon_re81, s2090, s2092, koff_re81, s1125), ...
Error in amimodel (line 130)
                        model = fun();
Error in amiwrap (line 122)
        model = amimodel(symfun,modelname);
Error in optimize_ASTHMA_V40_M07 (line 81)
    amiwrap(modelName,modelAMICI,thisDir,false);

Finally, I have also seen the error in complex formation with different substrates (i.e. heterodimerization as opposed to homodimerization). Ignoring the reverse direction, I have a function
"Complex_Formation_2_substrates__rev" and a reaction for the consumption of substrate1:
`-kon*substrate1*substrate2`
In this case, the problem occurs if substrate1 and substrate2 both attain slightly negative values due to numerical errors, and this has actually occurred in my current model.

**Comment by FFroehlich** [comment]
In practice, AMICI does support max functions, but requires max functions to be specified as "am_max", which was only recently changed and apparently not accounted for in the MATLAB sbml import. Can you try replacing all `max(...)` functions by `am_max(...)` in ASTHMA_V40_M07_syms?

The general issue of enforcing positive values is not that easy to solve. The CVODES guide gives the following advice:

> Advice on controlling unphysical negative values. In many applications, some components in the true solution are always positive or non-negative, though at times very small. In the numerical solution, however, small negative (hence unphysical) values can then occur. In most cases, these values are harmless, and simply need to be controlled, not eliminated. The following pieces of advice are relevant.
(1) The way to control the size of unwanted negative computed values is with tighter absolute tolerances. Again this requires some knowledge of the noise level of these components, which may or may not be different for different components. Some experimentation may be needed.
(2) If output plots or tables are being generated, and it is important to avoid having negative numbers appear there (for the sake of avoiding a long explanation of them, if nothing else), then eliminate them, but only in the context of the output medium. Then the internal values carried by the solver are unaffected. Remember that a small negative value in y returned by cvodes, with magnitude comparable to abstol or less, is equivalent to zero as far as the computation is concerned.
(3) The user’s right-hand side routine f should never change a negative value in the solution vector y to a non-negative value, as a ”solution” to this problem. This can cause instability. If the f routine cannot tolerate a zero or negative value (e.g. because there is a square root or log of it), then the offending value should be changed to zero or a tiny positive number in a temporary variable (not in the input y vector) for the purposes of computing f(t,y).
(4) Positivity and non-negativity constraints on components can be enforced by use of the recover-able error return feature in the user-supplied right-hand side function. However, because this option involves some extra overhead cost, it should only be exercised if the use of absolute tolerances to control the computed values is unsuccessful.

So probably the best way to implement this is by following point (3) and copying the values from the solver state to the model state and setting all negative values to 0. This will incur some overhead in the evaluation of all states, but a computationally more expensive solution is probably better than no solution at all, as long as this feature is optional. Probably the best place to do this are the solver functions `CVodeSolver::fxdot`, `CVodeSolver::fxBdot` etc.

**Comment by thomassligon** [comment]
I have tried am_max and it seems to be working as expected. This is probably all I need, but I think I should leave the issue open to see if we get any other comments. There is a differences between
the

1.  am_max solution
2. the non-negativity solutions above.

The first will stop the consumption reaction as soon as the state goes negative. As a result, since production might continue, the state might oscillate around zero.
The second will enforce positivity, setting the value of the state itself to zero. After that, it might still be produced and might still oscillate around zero.

**Comment by thomassligon** [comment]
I applied am_max to all potential functions and had this error:
Warning: AMICI ERROR: in module CVODES in function CVode : At t = 918.375 and h = 6.66067e-08, the error test failed repeatedly or with |h| = hmin.  
Warning: AMICI forward simulation failed at t = 918.374750:
AMICI failed to integrate the forward problem

What is the error test?

**Comment by FFroehlich** [comment]
The error test refers to a part of the adaptive stepsize (`h`) selection algorithm employed by CVODES that ensures that specified tolerances are met. `|h| = hmin` would indicate that the stepsize cannot be reduced any further and thus the specified integration tolerances cannot be met, `error test failed repeatedly` would indicate that the maximum number of step size adaptations in a single iteration has been reached. 

There is not way of specifying hmin or the maximum number of error failures as we deemed default values reasonable and accepted the notion that integration will sometimes fail.
