### ISSUE TITLE
Error when building deltaqB with 'Xcode Clang++'.

### ISSUE THREAD

**Issue by hjdudley** [ICB-DCM/AMICI#49]
Hello,

I am using AMICI with Matlab R_2016b and Xcode version 8.2.1 for a DAE model.  When I call:  amiwrap(modelname,’example_model_syms’,dir,o2flag) to compile my model,
Mex completes successfully until I get the following errors:

"deltaqB | Building with 'Xcode Clang++'.
Error using mex
/Users/harry/GitHub/AMICI/models/MEC/MEC_deltaqB.cpp:17:5: error:
use of undeclared identifier 'ip'
for(ip = 0; ip<np; ip++) {
    ^
/Users/harry/GitHub/AMICI/models/MEC/MEC_deltaqB.cpp:17:13: error:
use of undeclared identifier 'ip'
for(ip = 0; ip<np; ip++) {
            ^
/Users/harry/GitHub/AMICI/models/MEC/MEC_deltaqB.cpp:17:20: error:
use of undeclared identifier 'ip'
for(ip = 0; ip<np; ip++) {
                   ^
/Users/harry/GitHub/AMICI/models/MEC/MEC_deltaqB.cpp:18:15: error:
use of undeclared identifier 'ip'
switch (plist[ip]) {
              ^
4 errors generated.

Error in amimodel/compileC (line 379)
            eval(['mex ' DEBUG COPT ...

Error in amiwrap (line 90)
    model.compileC();"

Every time the MEC_deltaqB.cpp file is generated, it is missing the line:
int ip;
I am not sure why this line is not being generated.  It may be a bug or a user error.

Best,
Harry Dudley

**Comment by FFroehlich** [comment]
Hi Harry,

thanks for letting me know, the IDAS interface interface is currently in a bad shape since it's been a while since we last actively used it in a project. However, I tried to reproduce your problem and it is indeed a bug, but easy to fix:

Just remove the `~` in front of strcmp(this.funstr,'sxdot') in line 37 of ./@amifun/printLocalvars.m

There are some more problems with the IDAS interface, so you need an updated version of ./include/idawrap.h : [idawrap.h.zip](https://github.com/ICB-DCM/AMICI/files/720092/idawrap.h.zip)

Please keep in mind that the DAE part has not been tested as extensively and it is certainly possible that the computations are incorrect.

If you encounter any problems just let me know.

Best
Fabian
