### ISSUE TITLE
CVodes doesn't handle large `tout` well.

### ISSUE THREAD

**Issue by FFroehlich** [ICB-DCM/AMICI#558]
Passing large (~1e300) `tout`s to `solver->solver` may lead to `NaN` values in simulation results. 

I suppose some t+h != t but t-(t+h) == 0 due to float precision and this results in division by zero, which produces to NaN values. I don't want to spend too much time on following this up in more detail but I think we can't really expect the solver to behave well for such extreme timepoints and we probably never need to.

This happens during steady state simulation after a fairly small number of steps (~500), so I suppose that the solver is reaching a "steady state" after ~200 steps but tolerance are too tight such that it continues simulating and multiplying `tout` by 10 until it crashes due to `NaN` values.

Best way to prevent this and provide more meaningful error messages (took a while to debug) is probably limiting the `tout` to something more reasonable (1e100?) and producing an according error message with the suggestion to losen tolerances. Any suggestsions for a good limit @paulstapor @dweindl ?

**Comment by dweindl** [comment]
Is there a way to check ` t+h != t but t-(t+h) == 0` ourselves and issue a warning based on that, so that we can avoid a hard threshold?

**Comment by paulstapor** [comment]
One could think about doing so in the loop over the tout in solveForwardProblem or in the steadystateProblem

**Comment by paulstapor** [comment]
Well, I do not see a reasonable a priori limit...
However: If a steady state is not reached after 1e20, there are good chances to not reach it at any time, right? Maybe one possibility:
16 digits is about double precision, so the least we would want to go might be 1e16 (since in most cases, inputs etc. are somewhere in the order of [1e-3, 1e3]. I think, if we go up to 1e32 or something similar, we should really, really be safe. Whatever lies above this range, which an ODE solver spits out for my personal application, I would not trust anyhow... So I think we don't need to got any further than that...

**Comment by FFroehlich** [comment]
`h` (step size) is an internal variable computed by CVodes. I am not sure though whether we have access to it in CVodes. We might extend checkFinite though to 
- [ ] check for large values in `t` (not `ts`, we can probably remove that check as `inf` is a reasonable value to have with the equilibration code)
- [ ] check for NaNs in `x`. I always thought you could not end up with NaNs in `x` without having NaNs in `xdot`,  but apparently it is possible.
