### ISSUE TITLE
Add requirements.txt and use this for setting up venv

### ISSUE THREAD

**Issue by dweindl** [ICB-DCM/AMICI#595]
... instead of having dependencies listed in multiple places (.travis.yml, scripts/install*, ...)

**Comment by yannikschaelte** [comment]
I had differentiated the dependencies between travis and rtd, because on a previous project I had seen that rtd cannot deal with a full installation time-wise, so there I only wanted the really necessary files (in .rtd_pip_reqs.txt). that also sped up docs compilation considerably.

What could definitely be simplified is the setup.py:install[test] vs. the .travis.yml vs. the .travis_pip_reqs.txt. Here, I would agree that it is better to, if possible, have dependencies only in one place instead of three.

**Comment by yannikschaelte** [comment]
sorry, wrong project :) but certainly applies as well :) :)

**Comment by dweindl** [comment]
Maybe `setup_requires` can do the job. Problem is, that this is executed too late.
