### ISSUE TITLE
initialConcentration set to zero if not defined in SBML model

### ISSUE THREAD

**Issue by LeonardSchmiester** [ICB-DCM/AMICI#674]
We had the case, where only the `initialAmount` was set in the SBML model but not `initialConcentration`. AMICI then set the `initialConcentration` to zero. Maybe we should give a warning in that case.

**Comment by yannikschaelte** [comment]
Or maybe just use the value from initialAmount if initialConcentration is not given (both are exclusive by sbml standard). On the meaning of both see here: http://sbml.org/Special/specifications/sbml-level-2/version-1/html/

**Comment by dweindl** [comment]
Yes, should be implemented correctly. For those conversions we will also need to take units into account, which is not really done so far and a possible source of error.

**Comment by paulstapor** [comment]
I'm just stumbling across that "error" as well in the project with Philipp. We had this problem in 6 sbml-files out of some hundreds. It turned out that all those files were actually just mislabeled: They did not provide any more information on how to map amounts via units and volumes to concentrations, but only provided amounts...

So: If no units are defined, or for all species the attribute "hasOnlySubstanceUnits" is set to true, then I would suggest to map this 1:1 on "intialConcentration", since we don't have any information to do better.
We should issue a warning anyhow in this case...

But I think that >90% of the models which have this issue are just mislabeled/not properly defined...
