### ISSUE TITLE
‘inf’ was not declared in this scope

### ISSUE THREAD

**Issue by cemale** [ICB-DCM/AMICI#810]
While compiling an SBML model using steps shown in example_steadystate, below error reported. The example runs okay but my own SBML model results in this error. Thanks for the help..

MyModel_xdot.cpp: In function ‘void xdot_MyModel(realtype*, realtype, const realtype*, const realtype*, const realtype*, const realtype*, const realtype*)’:
MyModel_xdot.cpp:13:15: error: ‘inf’ was not declared in this scope
     xdot[0] = inf.0*flux_r0 - inf.0*flux_r1;
               ^~~
MyModel_xdot.cpp:13:15: note: suggested alternative: ‘ynf’
     xdot[0] = inf.0*flux_r0 - inf.0*flux_r1;
               ^~~
               ynf

**AMICI version and system environment**
Ubuntu-Linux, python.v3.7.4-anaconda, amici.v0.10.11

**Comment by FFroehlich** [comment]
That error reminds me of https://github.com/ICB-DCM/AMICI/issues/381

Is there any way you are using symengine instead of sympy?

**Comment by cemale** [comment]
I only have sympy 1.4 in conda-list, no symengine..

**Comment by FFroehlich** [comment]
Just to make sure - you are using the python interface to build your model right?

I don't see anything immediate that would explain your issues, is it possible to provide the sbml file you were using?

**Comment by cemale** [comment]
Here are the sbml and python script I am using. 

[mymodel.zip](https://github.com/ICB-DCM/AMICI/files/3658825/mymodel.zip)

**Comment by dweindl** [comment]
Dear @cemale, I can't seem to reproduce your error. Are you sure you uploaded the correct model? (In your output above, the model is called `MyModel`, whereas the one you uploaded is `BigModelPARCDL4`.)

**Comment by cemale** [comment]
Hi, I did not want to bother you with my arbitrary model name in the first comment, I always used the "BigModelPARCDL4" (changed the naming in the error message :) ). Actually, I get passed this error by somehow calling/creating the model in another folder. It now creates a directory containing 62 items but when tried to run the model, it does not have any parameters (model.getParameterList() returns () ). Again, I am using the xml model I sent.

**Comment by dweindl** [comment]
Alright. I did not find any parameter named in a way that could explain your issue above. I considered that done. Let us know if anything changes.

> It now creates a directory containing 62 items but when tried to run the model, it does not have any parameters (model.getParameterList() returns () ).

This is due to your line: 
` constantParameters = [params.getId() for params in sbml_model.getListOfParameters()]`.

With your current model, `print(model.getFixedParameterIds())` will show all your parameters and `print(model.getFixedParameters())` the respective values. (See https://icb-dcm.github.io/AMICI/classamici_1_1_model.html)

`model.getParameterList()` might not be what you are looking for. This does not provide you parameter names or values, but a list of parameter indices with respect to which you want to compute sensitivities (see doc above).

If you only want to run forward simulations, the current model is fine. If you want to compute sensitivities, you may want to delete that line. And change
```
sbml_importer.sbml2amici(model_name,
model_output_dir,
verbose=True,
constantParameters=constantParameters)
```
to
```
sbml_importer.sbml2amici(model_name,
model_output_dir,
verbose=True)
```

After that you will find your parameter IDs and values in `model.getParameterIds()` and ``model.getParameters()`, respectively.
