### ISSUE TITLE
help with event

### ISSUE THREAD

**Issue by ramosone** [ICB-DCM/AMICI#833]
Hi, sorry if its no the right place
can anyone explain how the events work on AMICI
for example:
% events fire when there is a zero crossing of the root function
model.event(1) = amievent(x3-x2,0,t);
what does this do? when x3-x2=0, what happens to t?

I am interested in  setting an event like:
if I have state1= -var1
how do I set an event when state1<1e-12 either state1=0 or var1=0

**Comment by FFroehlich** [comment]
Hi,

this is the right place to ask!
You can have a look at the documentation of amievent:
```
function AE = amievent(trigger,bolus,z)
            % amievent constructs an amievent object from the provided input.
            %
            % Parameters:
            %  trigger: trigger function, the event will be triggered on
            %      at all roots of this function
            %  bolus: the bolus that will be added to all states on every
            %      occurence of the event
            %  z: the event output that will be reported on every occurence
            %      of the event
            %
            % Return values:
            %  AE: amievent object
            %
```

Assuming you have a system 
```
model.x = [state1,var1],
```
you can set state1 to 0 as soon as state1<1e-12 by adding the following event:
```
model.event(1) = amievent(state1-1e-12,[-state1,0],[])
```
This will add an event that triggers adds `[-state1,0]` to the state vector, effectively setting state1 to zero. To set state1 and var1 to zero use the bolus `[-state1,-var1]`. 

In case you are trying to prevent state1 from becoming negative, I would advise against this approach as events are computationally very costly for the integration of the problem and in my experience, the integrator will become stuck in the area where states become negative. 
Usually the best way to control negative states is through integration tolerances. If even small negative values are a problem because you are, for example, using `log` in the right hand side of your ordinary differential equation, we generally recommend to use `am_max(x,0)` in the respective places instead of forcing the `x` to zero.

**Comment by ramosone** [comment]
Thank you very much Both :) 
With this I should make it work.
I am trying then first this am_max to avoid having a costly simulation
where in maybe state1=-amax(var1,0)
